//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DAYMAY
    {
        public DAYMAY()
        {
            this.DANGKYTIETHOCs = new HashSet<DANGKYTIETHOC>();
            this.MAYTINHs = new HashSet<MAYTINH>();
        }
        [Key]
        public string MADM { get; set; }
        public string TENDM { get; set; }
        public int MATT { get; set; }
    
        public virtual ICollection<DANGKYTIETHOC> DANGKYTIETHOCs { get; set; }
        public virtual ICollection<MAYTINH> MAYTINHs { get; set; }
        public virtual TRANGTHAI TRANGTHAI { get; set; }
    }
}
